name: Release
on:
  push:
    branches:
      - master
    tags:
      - "argsh-*"
  pull_request:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ startsWith(github.ref, 'refs/tags/argsh-')
            && format('type=match,pattern=argsh-(.*),group=1,value={0}', github.ref_name)
            || 'type=sha,format=long' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and release Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/argsh-') }}
          provenance: false
          platforms: linux/386,linux/amd64,linux/arm64,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment: release
    needs: [docker]
    if: startsWith(github.ref, 'refs/tags/argsh-')
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Upload release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp argsh.min.sh argsh
          sha256sum argsh > sha256sum.txt
          gh release create "${TAG_NAME}" --draft --title "argsh ${TAG_NAME#argsh-}" --generate-notes
          gh release upload "${TAG_NAME}" --clobber argsh sha256sum.txt