name: argsh tests
on:
  push:
    branches:
      - master
    paths:
      - 'libraries/**'
      - '.bin/**'
      - 'test/**'
  pull_request:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Direnv
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Lint
        run: |
          argsh lint
      - name: Test
        run: |
          argsh test

  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Direnv
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Build
        run: |
          argsh minify
      - name: Insync
        run: |
          git diff --exit-code
      - name: Lint
        run: |
          argsh lint -m
      - name: Test
        run: |
          argsh test -m
  
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Direnv
        uses: HatsuneMiku3939/direnv-action@v1
      - name: Coverage
        run: |
          argsh coverage